name: deploy aws account
run-name: ${{ inputs.account }} / ${{ inputs.region }} / ${{ inputs.component }} / ${{ inputs.terragrunt_action }}

on:
  workflow_call:
    inputs:
      account:
        required: true
        type: string
      region:
        required: true
        type: string
      component:
        required: true
        type: string
      terragrunt_action:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      account:
        default: all
        options:
          - all
          - mgmt
        required: true
        type: choice
      region:
        default: all
        options:
          - all
          - _global
          - ca-central-1
          - us-east-1
          - us-east-2
        required: true
        type: choice
      component:
        default: all
        options:
          - all
          - vpc_default
        required: true
        type: choice
      terragrunt_action:
        default: plan
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice

permissions:
  contents: read
  id-token: write

jobs:
  account:
    strategy:
      matrix:
        account: ${{ fromJson(inputs.account == 'all' && '["mgmt"]' || format('["{0}"]', inputs.account)) }}
    uses: ./.github/workflows/reusable_deploy_aws_regions.yaml
    with:
      account: ${{ matrix.account }}
      region: ${{ inputs.region }}
      component: ${{ inputs.component }}
      terragrunt_action: ${{ inputs.terragrunt_action }}
    secrets: inherit
